FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie
RUN apt-get update && apt-get install -y ruby \
  && rm -rf /var/lib/apt/lists/*

ADD . /app
CMD modprobe w1-gpio && modprobe w1-therm & ruby /app/my_app.rb
